version: '3'

services:
  db:
    image: mysql:5.7
    ports:
      - 3360:3306
    environment:
      MYSQL_DATABASE: gorm_mysql
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: gorm_mysql
      MYSQL_PASSWORD: gorm_mysql
